# 示例配置文件

# 数据库配置
databases:
  - name: "postgres_db"
    driver: "postgres"
    host: "10.0.1.5"
    port: 5432
    user: "postgres"
    password: "123456"
    database: "crud_test"
  
  - name: "mysql_db"
    driver: "mysql"
    host: "10.0.1.5"
    port: 3306
    user: "root"
    password: "123456"
    database: "crud_test"

# 表配置
tables:
  - name: "users"
    database: "postgres_db"
    path_prefix: "/users"
    field_map:
      id: "id"
      username: "username"
      email: "email"
      full_name: "full_name"
      created_at: "created_at"
    list_fields:
      - "id"
      - "username"
      - "email"
    detail_fields:
      - "id"
      - "username"
      - "email"
      - "full_name"
      - "created_at"
    handler_filters:
      - "save"
      - "delete"
      - "get"
      - "list"
      - "table"
  
  - name: "products"
    database: "mysql_db"
    path_prefix: "/products"
    field_map:
      id: "id"
      name: "name"
      description: "description"
      price: "price"
      stock: "stock"
      created_at: "created_at"
    list_fields:
      - "id"
      - "name"
      - "price"
      - "stock"
    detail_fields:
      - "id"
      - "name"
      - "description"
      - "price"
      - "stock"
      - "created_at"
    handler_filters:
      - "save"
      - "delete"
      - "get"
      - "list"
      - "table" 