# ApiAgent Consul配置文件
# 此文件需要上传到Consul KV存储中，键为apiagent/config

# 数据库配置
databases:
  - name: "ecommerce"
    driver: "postgres"
    host: "10.0.1.5"
    port: 5432
    user: "postgres"
    password: "123456"
    database: "ecommerce_db"
  
  - name: "crm"
    driver: "postgres"
    host: "10.0.1.5"
    port: 5432
    user: "postgres"
    password: "123456"
    database: "crm_db"
  
  - name: "inventory"
    driver: "postgres"
    host: "10.0.1.5"
    port: 5432
    user: "postgres"
    password: "123456"
    database: "inventory_db"

# 表配置
tables:
  # 电子商务数据库表
  - name: "products"
    database: "ecommerce"
    path_prefix: "/ecommerce/products"
    field_map:
      id: "id"
      name: "name"
      description: "description"
      price: "price"
      stock: "stock"
      category_id: "category_id"
      created_at: "created_at"
      updated_at: "updated_at"
    list_fields:
      - "id"
      - "name"
      - "price"
      - "stock"
      - "category_id"
    detail_fields:
      - "id"
      - "name"
      - "description"
      - "price"
      - "stock"
      - "category_id"
      - "created_at"
      - "updated_at"
    handler_filters:
      - "save"
      - "delete"
      - "get"
      - "list"
      - "table"
  
  - name: "categories"
    database: "ecommerce"
    path_prefix: "/ecommerce/categories"
    field_map:
      id: "id"
      name: "name"
      description: "description"
      parent_id: "parent_id"
      created_at: "created_at"
      updated_at: "updated_at"
    list_fields:
      - "id"
      - "name"
      - "parent_id"
    detail_fields:
      - "id"
      - "name"
      - "description"
      - "parent_id"
      - "created_at"
      - "updated_at"
    handler_filters:
      - "save"
      - "delete"
      - "get"
      - "list"
      - "table"
  
  - name: "users"
    database: "ecommerce"
    path_prefix: "/ecommerce/users"
    field_map:
      id: "id"
      username: "username"
      email: "email"
      full_name: "full_name"
      phone: "phone"
      address: "address"
      is_active: "is_active"
      created_at: "created_at"
      updated_at: "updated_at"
    list_fields:
      - "id"
      - "username"
      - "email"
      - "full_name"
      - "is_active"
    detail_fields:
      - "id"
      - "username"
      - "email"
      - "full_name"
      - "phone"
      - "address"
      - "is_active"
      - "created_at"
      - "updated_at"
    handler_filters:
      - "save"
      - "delete"
      - "get"
      - "list"
      - "table"
  
  - name: "orders"
    database: "ecommerce"
    path_prefix: "/ecommerce/orders"
    field_map:
      id: "id"
      user_id: "user_id"
      total_amount: "total_amount"
      status: "status"
      payment_method: "payment_method"
      shipping_address: "shipping_address"
      created_at: "created_at"
      updated_at: "updated_at"
    list_fields:
      - "id"
      - "user_id"
      - "total_amount"
      - "status"
      - "created_at"
    detail_fields:
      - "id"
      - "user_id"
      - "total_amount"
      - "status"
      - "payment_method"
      - "shipping_address"
      - "created_at"
      - "updated_at"
    handler_filters:
      - "save"
      - "get"
      - "list"
      - "table"
  
  - name: "order_items"
    database: "ecommerce"
    path_prefix: "/ecommerce/order_items"
    field_map:
      id: "id"
      order_id: "order_id"
      product_id: "product_id"
      quantity: "quantity"
      price: "price"
      subtotal: "subtotal"
      created_at: "created_at"
    list_fields:
      - "id"
      - "order_id"
      - "product_id"
      - "quantity"
      - "price"
      - "subtotal"
    detail_fields:
      - "id"
      - "order_id"
      - "product_id"
      - "quantity"
      - "price"
      - "subtotal"
      - "created_at"
    handler_filters:
      - "get"
      - "list"
      - "table"
  
  # CRM数据库表
  - name: "customers"
    database: "crm"
    path_prefix: "/crm/customers"
    field_map:
      id: "id"
      company_name: "company_name"
      contact_name: "contact_name"
      email: "email"
      phone: "phone"
      address: "address"
      industry: "industry"
      annual_revenue: "annual_revenue"
      employee_count: "employee_count"
      status: "status"
      created_at: "created_at"
      updated_at: "updated_at"
    list_fields:
      - "id"
      - "company_name"
      - "contact_name"
      - "email"
      - "industry"
      - "status"
    detail_fields:
      - "id"
      - "company_name"
      - "contact_name"
      - "email"
      - "phone"
      - "address"
      - "industry"
      - "annual_revenue"
      - "employee_count"
      - "status"
      - "created_at"
      - "updated_at"
    handler_filters:
      - "save"
      - "delete"
      - "get"
      - "list"
      - "table"
  
  - name: "contacts"
    database: "crm"
    path_prefix: "/crm/contacts"
    field_map:
      id: "id"
      customer_id: "customer_id"
      first_name: "first_name"
      last_name: "last_name"
      position: "position"
      email: "email"
      phone: "phone"
      is_primary: "is_primary"
      created_at: "created_at"
      updated_at: "updated_at"
    list_fields:
      - "id"
      - "customer_id"
      - "first_name"
      - "last_name"
      - "position"
      - "email"
      - "is_primary"
    detail_fields:
      - "id"
      - "customer_id"
      - "first_name"
      - "last_name"
      - "position"
      - "email"
      - "phone"
      - "is_primary"
      - "created_at"
      - "updated_at"
    handler_filters:
      - "save"
      - "delete"
      - "get"
      - "list"
      - "table"
  
  - name: "opportunities"
    database: "crm"
    path_prefix: "/crm/opportunities"
    field_map:
      id: "id"
      customer_id: "customer_id"
      contact_id: "contact_id"
      title: "title"
      description: "description"
      value: "value"
      stage: "stage"
      probability: "probability"
      expected_close_date: "expected_close_date"
      assigned_to: "assigned_to"
      created_at: "created_at"
      updated_at: "updated_at"
    list_fields:
      - "id"
      - "customer_id"
      - "title"
      - "value"
      - "stage"
      - "probability"
      - "expected_close_date"
    detail_fields:
      - "id"
      - "customer_id"
      - "contact_id"
      - "title"
      - "description"
      - "value"
      - "stage"
      - "probability"
      - "expected_close_date"
      - "assigned_to"
      - "created_at"
      - "updated_at"
    handler_filters:
      - "save"
      - "delete"
      - "get"
      - "list"
      - "table"
  
  # 库存管理数据库表
  - name: "warehouses"
    database: "inventory"
    path_prefix: "/inventory/warehouses"
    field_map:
      id: "id"
      name: "name"
      location: "location"
      capacity: "capacity"
      manager: "manager"
      contact_phone: "contact_phone"
      is_active: "is_active"
      created_at: "created_at"
      updated_at: "updated_at"
    list_fields:
      - "id"
      - "name"
      - "location"
      - "manager"
      - "is_active"
    detail_fields:
      - "id"
      - "name"
      - "location"
      - "capacity"
      - "manager"
      - "contact_phone"
      - "is_active"
      - "created_at"
      - "updated_at"
    handler_filters:
      - "save"
      - "delete"
      - "get"
      - "list"
      - "table"
  
  - name: "items"
    database: "inventory"
    path_prefix: "/inventory/items"
    field_map:
      id: "id"
      sku: "sku"
      name: "name"
      description: "description"
      category_id: "category_id"
      unit_price: "unit_price"
      unit_cost: "unit_cost"
      reorder_level: "reorder_level"
      reorder_quantity: "reorder_quantity"
      is_active: "is_active"
      created_at: "created_at"
      updated_at: "updated_at"
    list_fields:
      - "id"
      - "sku"
      - "name"
      - "unit_price"
      - "unit_cost"
      - "reorder_level"
      - "is_active"
    detail_fields:
      - "id"
      - "sku"
      - "name"
      - "description"
      - "category_id"
      - "unit_price"
      - "unit_cost"
      - "reorder_level"
      - "reorder_quantity"
      - "is_active"
      - "created_at"
      - "updated_at"
    handler_filters:
      - "save"
      - "delete"
      - "get"
      - "list"
      - "table"
  
  - name: "inventory"
    database: "inventory"
    path_prefix: "/inventory/stock"
    field_map:
      id: "id"
      warehouse_id: "warehouse_id"
      item_id: "item_id"
      quantity: "quantity"
      location_code: "location_code"
      last_counted_at: "last_counted_at"
      created_at: "created_at"
      updated_at: "updated_at"
    list_fields:
      - "id"
      - "warehouse_id"
      - "item_id"
      - "quantity"
      - "location_code"
    detail_fields:
      - "id"
      - "warehouse_id"
      - "item_id"
      - "quantity"
      - "location_code"
      - "last_counted_at"
      - "created_at"
      - "updated_at"
    handler_filters:
      - "save"
      - "get"
      - "list"
      - "table" 