# 测试用配置文件

# 数据库配置
databases:
  - name: "test_db"
    driver: "postgres"
    host: "10.0.1.5"
    port: 5432
    user: "postgres"
    password: "123456"
    database: "crud_test"

# API前缀配置
api_prefix: "/api"

# 表配置
tables:
  - name: "users"
    database: "test_db"
    path_prefix: "/users"
    field_map:
      id: "id"
      username: "username"
      email: "email"
    list_fields:
      - "id"
      - "username"
      - "email"
    detail_fields:
      - "id"
      - "username"
      - "email"
      - "created_at"
    handler_filters:
      - "table"
      - "list"
      - "save"
      - "delete"
      - "get"
  - name: "products"
    database: "test_db"
    path_prefix: "/ecommerce/products"
    field_map:
      id: "id"
      name: "name"
      price: "price"
    list_fields:
      - "id"
      - "name"
      - "price"
    detail_fields:
      - "id"
      - "name"
      - "price"
      - "created_at"
    handler_filters:
      - "list"
      - "save"
  - name: "categories"
    database: "test_db"
    path_prefix: "/ecommerce/categories"
    field_map:
      id: "id"
      name: "name"
    list_fields:
      - "id"
      - "name"
    detail_fields:
      - "id"
      - "name"
      - "created_at"
    handler_filters:
      - "list"
      - "get" 